### ISSUE TITLE
LC_Page_Admin_Products_Product::lfHasSameProductImage() 「$this->objUpFile」って存在しないかと

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube2#100]

**Comment by so-amuamu** [comment]
古いコードが残っている模様。
引数渡しに書き換えが必要。

**Comment by seasoftjapan** [comment]
テストデータを作成し、変更対象以外の画像項目での利用を検出できない (おそらく不具合) ことを確認した。

未検証だが、(「商品登録」画面で登録した商品では該当するデータは発生しないと思うが)「商品登録CSV」画面ではテストデータ同様のデータ状態を発生させられると思う。

**Comment by okazy** [comment]
#278 こちらで修正されましたのでクローズします。
