### ISSUE TITLE
/guide以下にアクセスすると500エラー（privacy.php除く）

### ISSUE THREAD

**Issue by clicktx** [EC-CUBE/ec-cube2#1005]
/guide/index.phpを含む下記URLでは500エラーとなります。

- usage.php
- charge.php
- kiyaku.php
- about.php

/guide/privacy.php 以外はPC、sphone用のテンプレートが無いためと思われます。
（以前は携帯サイト用に使われていた）

通常は上記ページに対してはリンクがないので問題ないと思いますが、
/guide/privacy.php は公開されているためクローラーが/guide(/index.php) にアクセスしてくるようで、気が付きました。

せっかくならテンプレートを作って使う方向にするか、不要なら削除するか、になるでしょうか？

**Comment by nanasess** [comment]
@clicktx 削除してよさそうですね。
