### ISSUE TITLE
セッションデータに保存される配送商品のコンテンツデータは必要？

### ISSUE THREAD

**Issue by clicktx** [EC-CUBE/ec-cube2#1007]
dtb_session.sess_dataに保存されるデータにshipping itemsに関する無駄な情報が多い気がします。

1. カートに商品を追加
2. shoppingプロセスをすすんで「入力内容のご確認画面」まで進む（途中まででも良いかも）
3. セッションデータに商品データ全て（？）が保存される

main_commentやsub_title1〜、sub_comment1〜等、dtb_productsにあるデータが（恐らく）すべて含まれるため、商品の説明コンテンツが長いほどデータ量が多くなります。

何かに使われる気はしないのですが、必要なデータなのでしょうか？
かなり昔にMySQLでセッションデータがオーバーフローする現象がある、というような書き込みを見かけた気がしますが、、、

**Comment by clicktx** [comment]
DBによる違いはありますでしょうか？
検証環境はphp7.4+postgresqlです。

ショッピングプロセスで配送先が確定された時の更新で追加される感じでした。

セッションの中身をJSONにしたものを貼っておきます。
https://gist.github.com/clicktx/2d0e12842620505f56d40349c6fcc3a4

**Comment by clicktx** [comment]
ざっとコードを追うと下記部分が怪しい感じですかね（未検証）

https://github.com/EC-CUBE/ec-cube2/blob/74eaa0a4bacce4c115fa1abbcd0802e4e734590f/data/class/helper/SC_Helper_Purchase.php#L371-L398

ここで代入していそう
```php
$product = &$objProduct->getDetailAndProductsClass($product_class_id);
$arrItems['productsClass'] = $product;
```

**Comment by nanasess** [comment]
@clicktx ありがとうございます。こちらでも確認してみますね
