### ISSUE TITLE
買い物プロセス ゲスト購入でお客様情報入力へ戻ると生年月日が補完されない

### ISSUE THREAD

**Issue by clicktx** [EC-CUBE/ec-cube2#1008]
細かい事なのですが...
ゲスト購入でお届け先情報の生年月日を設定した時、事項以降に進んだ後にお届け先情報入力画面へ戻ると月、日のみ補完されません。

![スクリーンショット 2024-09-19 20 57 30](https://github.com/user-attachments/assets/916a1dd4-4ce0-4900-ba52-5e28b679e1b4)

**Comment by nanasess** [comment]
月、日が1桁の場合に発生する感じですかね？

**Comment by clicktx** [comment]
@nanasess 確認したところ確かにそうですね。いずれの組み合わせでも2桁になると2桁の方は補完されているようです。

**Comment by nanasess** [comment]
@clicktx 
Smarty3 以降、 1 桁の場合はゼロ埋めしてはいけないんですけど、戻った際にゼロ埋めした月日が渡ってしまっている感じですね。。。

**Comment by clicktx** [comment]
@nanasess Smartyの仕様の影響なんですね。間がある時に修正してみます
