### ISSUE TITLE
プラグイン機能 テンプレートに対するトランスフォームが環境によって正常に動作しない

### ISSUE THREAD

**Issue by Yangsin** [EC-CUBE/ec-cube2#103]
PHPがリンクしているlibxmlのバージョンが2.7未満の場合に生じる問題

具体的な不具合
・テキストのみのテンプレート（主にメールテンプレート）の場合に、libxmlのバージョンが古いと記号類が数値参照形式になってしまう。
・長大なHTMLの場合、正常にパースできない

パース自体が失敗している場合に処理を迂回するような改修の必要性がありそうです。

詳細は下記コミュニティ内にて  http://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=12017&forum=10&post_id=55450#forumpost55450

※主にhetemlサーバーで生じる模様

[Tracからの転記](http://svn.ec-cube.net/open_trac/ticket/2224)

**Comment by so-amuamu** [comment]
2.17が対応するPHPバージョン次第。そのPHPが求めるlibxml2最低バージョンを確認して必要なら対処。

**Comment by nanasess** [comment]
PHP7.4以降では再現しないと思われますのでクローズします
