### ISSUE TITLE
スマートフォンで商品一覧の価格順が不正

### ISSUE THREAD

**Issue by izayoi256** [EC-CUBE/ec-cube2#106]
![20161110114516](https://cloud.githubusercontent.com/assets/1329505/20162856/43a18782-a73b-11e6-98d8-5f455428e21f.png)

**Comment by izayoi256** [comment]
javascriptのfor inで配列の順序が保証されていないことが原因

**Comment by 3tiles** [comment]
[旧Tracのチケット2555](http://svn.ec-cube.net/open_trac/ticket/2555)と同様の内容ですかね？
であれば、 #332 で修正してみました。

**Comment by chihiro-adachi** [comment]
#332 で対応
