### ISSUE TITLE
SC_FormParam::setHtmlDispNameArray() の判定が不適切

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube2#111]
誤
`if ($this->arrDefault[$key] != '') {`
正
`if (strlen($this->arrDefault[$key]) >= 1) {`

このバグを回避するため、LC_Page_Admin_Products_UploadCSV#lfSetParamDefaultValue() において、`$arrCSVFrame[$key]['default'] = '0';`  のように、数値を文字列としている。

**Comment by okazy** [comment]
# 380 で修正されましたのでクローズします。
