### ISSUE TITLE
新着情報管理　既存のデータを編集する際、フォームの日付の月の項目が未選択になってしまう

### ISSUE THREAD

**Issue by arisgi** [EC-CUBE/ec-cube2#136]
## 概要(Overview)
新着情報管理で登録済みの新着情報の編集を行おうとした際、
フォームの日付の月の項目が未選択になってしまう。

![image](https://user-images.githubusercontent.com/16891862/29903365-7b31670e-8e3e-11e7-9a3f-cf2ad90ed183.png)

## 期待する内容(Expect)  or 要望 (Requirement)
登録されている日付をフォームに表示したい。

## 再現手順(Procedure)
管理画面の「コンテンツ管理＞新着情報管理」にて
新着情報一覧の任意のデータの編集ボタンを押下。

### 環境 (environment)

ブランチ：improve/php7

+ PHP7環境
  - PHP: 7.1.8
  - DB: PostgreSQL 9.2.18
+ PHP5環境
  - PHP: 5.4.16
  - DB: MySQL 5.5.57

## 関連情報 (Ref)
なし

**Comment by 3tiles** [comment]
#160 の方にも書かれているかと思いますが、 #175 の[LC_Page_Admin_Contents.php部分の修正](https://github.com/EC-CUBE/eccube-2_13/pull/175/files#diff-a24773aea49c79b6ca2a59e8c8fc02e2)で本Issueは解消されているかと思うのですが、こちらはCloseされないんでしょうか？

**Comment by nanasess** [comment]
修正済みですので close します
