### ISSUE TITLE
プラグインなどで、admin(default)以下にないtplを呼び出そうとするとエラーになる

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube2#144]
From @nobuhiko on 5 Jul, 2017
Copied from original issue: nanasess/ec-cube-extended/issues/41

---

{include file='file:index.tpl'} という書き方に変更する必要がある

@see http://www.smarty.net/docs/ja/template.resources.tpl

**Comment by nanasess** [comment]
プラグイン側の問題なのでクローズします
