### ISSUE TITLE
Google Maps Platform APIキーに関わる不具合

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube2#216]
- 所在地入力ボタンが動作しない。(#156)
- 地図設定項目が正常に動作していない。(#156)

Google Maps Platform APIキーを設定できるようにする修正が必要となる

**Comment by so-amuamu** [comment]
APIキー不要なiframe呼び出しに切り替えるのは難しいですかね？

**Comment by nobuhiko** [comment]
所在地入力ボタンはAPIを直接呼んでいるので、なにか別の方法 https://qiita.com/akkey2475/items/81f4f94f17bfe5c7ce42 を使わないとダメだと思います

**Comment by nanasess** [comment]
この機能無くしちゃってもいいんじゃないです？？

**Comment by so-amuamu** [comment]
意見無ければ、無くしましょうか
地図追加プラグインとか別途だれかが作る感じで良い気がする

**Comment by nanasess** [comment]
#371 で修正
