### ISSUE TITLE
mtb_allowed_tag をブラックリスト方式に変更

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube2#230]
#224 から分離しました。
- テーブル名は、mtb_allowed_tag か。
- ブラックリストに初期登録する要素は、こんなところか。
  - script
  - html
  - body
  - head
  - title
  - meta
  - frame
  - frameset
  - object
  - embed
  - param
  - form
  - input
  - select
  - textarea
  - button
- ホワイトリスト・ブラックリストの切り替え対応とするのも可能かも。(プラグインでやれ?)

**Comment by nanasess** [comment]
2020年代のセキュリティ事情からすると、ブラックリスト方式ではセキュリティの担保が難しく、 #710 を実装することでより確実にセキュリティ担保可能なのでこちらはクローズします
