### ISSUE TITLE
商品種別IDの変数名がバラついている

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube2#274]
`$product_type_id` が正しいはず。
`$productTypeId` とか `$key` とか、やめる。

**Comment by nobuhiko** [comment]
issueはもうちょっと具体的に書きませんか？
自分へメモであるならいきなりプルリクでいいと思います

**Comment by seasoftjapan** [comment]
> issueはもうちょっと具体的に書きませんか？

現状、余力無く無理です。
本当にごめんなさい。

>自分へメモであるならいきなりプルリクでいいと思います

実装しておらず。。。
けど、いきなり PR が OK になると、それはそれで助かりますね。

さて、すれ違いなので、この辺で失礼したいと思います。

**Comment by nanasess** [comment]
#274 で対応済みですのでクローズします
