### ISSUE TITLE
Heroku button の不具合

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube2#287]
masterじゃないブランチをデフォルトにしているとbuttonがちゃんと動かない問題

https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2FEC-CUBE%2Fec-cube&template=https%3A%2F%2Fgithub.com%2FEC-CUBE%2Fec-cube/tree/4.0
↑4.0の場合はこうかけば動く。

**Comment by nanasess** [comment]
デフォルトブランチ変更に伴い修正されましたのでクローズします
