### ISSUE TITLE
CSV出力項目設定 multiselect2side の不具合

### ISSUE THREAD

**Issue by nomoto-neo** [EC-CUBE/ec-cube2#299]
管理画面のCSV出力項目設定の動きがおかしいようです。

具体的には「CSV出力する項目」から「CSV出力しない項目」へ移動した項目は、再度CSV出力する項目へ戻しても、登録時に反映されずDB上はCSV出力しない項目として登録されてしまいます。
一旦登録して画面がリフレッシュされたあとは、CSV出力しない項目からCSV出力する項目へ移動が可能になります。

かなり以前から発生していた問題ではないかと思いますが、上記のように一旦保存すれば操作できるし、この画面の使用頻度も少なかったので気にしていませんでした。

/html/user_data/packages/admin/jquery.multiselect2side/js/jquery.multiselect2side.js
が attr("selected", ～) というJQeury-1時代の書き方のままなのが原因なので prop("selected", ～) に書き換えれば良いようです。

このmultiselect2sideパッケージ自体の更新された新しいバージョンはネットで見つけられませんでした。

**Comment by nanasess** [comment]
#330 で修正されました
