### ISSUE TITLE
商品個別税率を一旦設定すると基本税率と連動できなくなる

### ISSUE THREAD

**Issue by nomoto-neo** [EC-CUBE/ec-cube2#304]
商品個別税率機能をオンにした状態で商品別の税率を一旦設定すると、商品別のdtb_tax_ruleレコードが作成されるが、その後に基本税率と同じ値に戻しても del_flg が立たずに商品別のdtb_tax_rule レコードに基本税率と同じ値が設定されるだけなので、その後に基本税率が変動してもその商品は基本税率の変化に連動しなくなってしまう。

基本税率と同じ値を設定されたら商品別レコードは del_flg=1 にする
※修正パッチだけの提供で申し訳ありません

[setTaxRuleForProduct_bug.txt](https://github.com/EC-CUBE/eccube-2_13/files/3533350/setTaxRuleForProduct_bug.txt)

#301 の投入有無は影響しません

**Comment by nanasess** [comment]
@nomoto-neo ありがとうございます。 #305 で PR してみました

**Comment by nomoto-neo** [comment]
@nanasess ありがとうございます

**Comment by chihiro-adachi** [comment]
#305 で修正
