### ISSUE TITLE
商品規格編集画面で無駄なレコードが登録されるのを防ぎ、受注編集時のエラーも防ぐ

### ISSUE THREAD

**Issue by nomoto-neo** [EC-CUBE/ec-cube2#308]
現状、
規格１が20種、規格２が5種というケースで商品規格画面で1種類だけチェックBOXを立てると、dtb_prodcts_class に1件の del_flg=0 レコードと、99件の無駄な del_flg=1 レコードが登録される（DB肥大）※ del_flg=9のレコードをinsertする事に意味があると思えないのですが。
また商品規格データを更新するたび全deleteして全insertしているため、上記の del_flg=1 のレコードがAUTO_INCREMENTを進めて product_class_id がどんどん進んでしまう（idの浪費）
また、チェックBOXをいったんオフにして更新すると、その後オンにして更新しても上記理由から product_class_id が変わってしまうため、その product_class_id を過去に受注していた場合、受注データの編集画面で更新ボタンがエラーになってしまう（データ関連性の破壊）

対策
・チェックBOXをオンにしていない規格パターンは dtb_products_class に登録しない
・チェックBOXをオフにしたとき、既に受注を受けている product_class_id は物理削除ではなく論理削除（del_flg=1）に。
・チェックBOXを再度オンにしたとき、過去の product_class_id を del_flg=0 にして復活させて再利用する
・受注編集画面で注文数を変更したとき、product_class_id が論理削除されていたら該当 product_class_id の在庫数の更新をしない

という修正を行なったのでご提供させてください。
[dtb_products_class_diet.diff.txt](https://github.com/EC-CUBE/eccube-2_13/files/3564573/dtb_products_class_diet.diff.txt)

**Comment by nobuhiko** [comment]
プルリク、覚えませんか・・・

**Comment by nomoto-neo** [comment]
時間をみて勉強します；

**Comment by nanasess** [comment]
@nomoto-neo PR 作っておきました。 #362
