### ISSUE TITLE
smartyタグに余計なスペースがあるとエラーになる

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube2#336]
`<!--{ if $menu.class_name != ""}` や `<!--{ $menu.class_name }-->` で Smarty Compiler: Syntax error in template が出てしまう

smarty3の問題と思われる

@see [https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22946&forum=4&post_id=95144#forumpost95144](https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=22946&forum=4&post_id=95144#forumpost95144)

**Comment by nanasess** [comment]
Smarty4 以降では対応が難しいためクローズします
