### ISSUE TITLE
お届け日に現在日時がセットされる

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube2#345]
https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=23041&forum=8&post_id=95473#forumpost95473

**Comment by 3tiles** [comment]
これ、Smarty(3.1.32〜)のバグが原因っぽいです。

https://github.com/smarty-php/smarty/issues/434

既に修正はされていて、次リリース(3.1.34)に含まれるはずですが、なかなかリリースに時間が掛かっているようですね。

https://github.com/smarty-php/smarty/issues/545
とかによれば、もうそろそろ3.1.34がリリースされそうな感じではありますが。

**Comment by nobuhiko** [comment]
3.1.34になったので改善したか確認しないとですね

**Comment by bbkids** [comment]
3.1.34で改善しているの確認出来ました。

**Comment by nanasess** [comment]
@bbkids ご確認ありがとうございます！
#344 で修正されたということでクローズします
