### ISSUE TITLE
data/module 以下の 古い PEAR ライブラリを置き換え

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube2#355]
## 内部の実装をネイティブ関数に置き換えたいライブラリ
- [ ] `HTTP_Request` -> curl

## PHP5以降の構文にリファクタリングしたいライブラリ
- [ ] Net_URL
- [ ] gdthumb

## Packagist で管理されているものに置き換えたいライブラリ
- [x] https://github.com/pear/Net_Socket
- [x] https://github.com/pear/Net_SMTP(#650)
- [ ] https://github.com/pear/Calendar (release タグが無いため dev-master を参照)
- [x] https://github.com/Setasign/FPDI

## 本体では使用していないため廃止したいライブラリ
- [x] PEAR_SOAP

**Comment by nobuhiko** [comment]
HTTP_Request は決済モジュールが生で呼んでいることが多いので、後方互換が重要かなと思います

**Comment by nanasess** [comment]
@nobuhiko そうですね。インターフェイスは共通化して、内部実装のみ curl に置き換えるイメージです
