### ISSUE TITLE
ResizeImage の廃止

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube2#356]
- ガラケー廃止、ネットワークの高速化、端末の高性能化で必要性が薄れてきたため
- パフォーマンスが悪く、トラフィックが集中した際にボトルネックになるため
- CDN を活用できないため

**Comment by tao-s** [comment]
最近はスマホでのパフォーマンス等が求められ、むしろ必要性は高くなっていると思います。

ただ、クエリパラメータで指定する現状の方式ではCDNとの相性が悪かったりと問題はあるので、```resizeImage/xxxx/yyyy/sample.jpg```の様な形式でキャッシュさせるなりの仕組みが必要だと思います。
あと、単にリサイズするのではなく、表示サイズ（端末のwindowサイズなど）に応じてリサイズ、minifyでファイル容量を減らすという仕組みにする必要があると思います。

**Comment by nobuhiko** [comment]
resize_image.php ですよね？そもそも2系ってほぼ使っていないような？

**Comment by nanasess** [comment]
今はもう使ってないと思います。 リサイズが必要ならば、 resize_image.php ではなく別の仕組みにした方が良いかと。

**Comment by seasoftjapan** [comment]
今の実装だと、画像を直接参照する方が、概ね早いですから。。。 パフォーマンスを真面目に考えるならば、キャシュが存在する画像は、PHP を介さずに出力するなどの工夫は必要だと思います。

**Comment by tao-s** [comment]
@seasoftjapan サーバの反応が速くても、例えば重い商品画像をリサイズせずに商品一覧で使ったりするとスマホで重くなります。
なので画像のリサイズ機能は残して欲しいです。
キャッシュの仕組みは、リサイズ後の画像の扱いです。

**Comment by nanasess** [comment]
@tao-s 
- 画像参照時に resize_image.php で動的にリサイズする実装は廃止
- 管理画面で画像登録時に自動的にリサイズする機能(gdthumbクラス)は残す

で、いかがでしょう？

**Comment by tao-s** [comment]
@nanasess あれサクっとどうにかする時とか便利だったんですけどねw

画像登録時だと使わないサムネイルも生成して容量食ったり管理画面重くなったりするので、初回参照（アクセス）時に生成するってのはどうでしょう？

**Comment by seasoftjapan** [comment]
前回のコメントに書いたような点も含め、有意な機能に改善され、EC-CUBE のデフォルトで利用されるならば、このプロジェクトで保守を続けても良いのかなと思います。後述のような代替機能が無いにしても、今の resize_image.php は無しかなと。

そういえば resize_image.php は、セッションの排他制御にも影響しましたね。(同一セッションの同時読み込みがブロックされたり、逆にブロックがうまくいかずにセッション変数を古い値で上書きしたり。)

> 画像登録時だと使わないサムネイルも生成して容量食ったり管理画面重くなったりするので、初回参照（アクセス）時に生成するってのはどうでしょう？

(生成は PHP で処理するとして) 画像の送出は PHP を介さないように実装いただけるのでしたら、基本的に賛成です。
記憶の範囲ですと、Apache でしたら、.htaccess + mod_rewrite で対応できたと思います。
IIS は、Web.config とかで同様に対応できるのか分からないですが、#357 が進めば、同様の対応は無理でも、強引に何とか体裁を保てる余地はありそうですね。

別の観点で、2.13 との互換性が損なわれそうな気もするので、それを良しとするかも課題でしょうか。(2.17 系のポリシーはどうなんでしたっけ?)

**Comment by nanasess** [comment]
現状の resize_image.php のインターフェイスを維持したまま、PHP を介さずリサイズ画像を静的に参照するように改修するのはあまりメリットが無いと思いますので、新たに作成するようにしましょう

**Comment by nobuhiko** [comment]
gdthumb はライセンス的にもメンテ的にも怪しいので、そっちも気になります

**Comment by nanasess** [comment]
現状、テンプレートからの参照はしていないのでクローズします
