### ISSUE TITLE
is there english / japanese documentation

### ISSUE THREAD

**Issue by jeraldpunx-gemsoft** [EC-CUBE/ec-cube2#375]
Hello, I want to learn more about this framework... just need english or japanese I can translate it anyway. It's hard to find on google cause I'm no japanese guy.
I want to know some basics just like 
if else, for loop, etc in front end.
I am slow learning and it's on D:\laragon\www\store2\data\Smarty\ with file name tpl
and the functions are on class folder... 

I just got this project from other boss but he don't know about this cause he's not programmer.
hope someone reply me fast here.

**Comment by nanasess** [comment]
@jeraldpunx-gemsoft Welcome to EC-CUBE2, thanks for the detailed issue.
Unfortunately, documentation in English is not active.
The following is the reference of the front end document.
https://www.smarty.net/docs/en/

Also, @onshopVN team is actively developing EC-CUBE in English.

**Comment by nanasess** [comment]
This issue has been inactive for a long time, so it will be closed.
