### ISSUE TITLE
What does LC, sf, lf, SC prefix stand for?

### ISSUE THREAD

**Issue by pquy1008** [EC-CUBE/ec-cube2#390]
I'm new to EC Cube, so I'm so sorry if this question is weird.
I know that a function with `lf` prefix is private/protect function,
sf prefix for public function.
But, for easy to remember, what does `lf, sf, LC`... really stand for?
Thank you so much.

**Comment by nanasess** [comment]
*[There are Japanese documents here.](http://svn.ec-cube.net/open_trac/wiki/EC-CUBE%E6%A8%99%E6%BA%96%E8%A6%8F%E7%B4%84)*

This naming convention is a remnant of PHP4 and  is now obsolete.


| Abbr | Dfn |
|------|-----------------|
| GC   | Global Class    |
| SC   | Share Class     |
| LC   | Local Class     |
| gf   | Global function |
| sf   | Share function  |
| lf   | local function  |

**Comment by pquy1008** [comment]
@nanasess I got it, thank you so much.
