### ISSUE TITLE
おすすめ商品管理で IN が使われている SQL が重い

### ISSUE THREAD

**Issue by mattintosh4** [EC-CUBE/ec-cube2#407]
下記二箇所の SQL で `IN` が使われているためデータ量が多いと重くなります。
DB のバージョンにもよるかもしれませんがこのクエリが長時間完了せず他のクエリが処理待ちの状態になり DB が応答しなくなります。（実際にサービスが停止したという問い合わせを受けたため確認しました）
`alldtl.product_id` を `IN` で絞り込むのであれば `EXISTS` を使った方が効率がいいのではないでしょうか。
環境は MySQL となります。PostgreSQL での検証はしておりません。

**修正提案箇所1**
https://github.com/EC-CUBE/ec-cube2/blob/5b82f42d471cdf3dace7522d58e20915320e6614/data/class/pages/admin/contents/LC_Page_Admin_Contents_RecommendSearch.php#L161

```php
 $where.= ' AND EXISTS (SELECT * FROM dtb_product_categories WHERE dtb_product_categories.product_id = alldtl.product_id AND ' . $tmp_where . ')'; 
```

**修正提案箇所2**
https://github.com/EC-CUBE/ec-cube2/blob/5b82f42d471cdf3dace7522d58e20915320e6614/data/class/pages/admin/contents/LC_Page_Admin_Contents_RecommendSearch.php#L166

```php
 $where .=    ' AND EXISTS (SELECT * FROM dtb_products_class WHERE dtb_products_class.product_id = alldtl.product_id AND product_code LIKE ?)'; 
```

**Comment by nanasess** [comment]
@mattintosh4 良さげですので、 Pull Request していただくことは可能でしょうか？

**Comment by okazy** [comment]
#409 が取り込まれましたのでこちらはクローズさせていただきます。
ありがとうございました！
