### ISSUE TITLE
csvダウンロード時に、エスケープ文字と判断される

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube2#467]
@see https://xoops.ec-cube.net/modules/newbb/viewtopic.php?topic_id=25241&forum=9&post_id=101812#forumpost101812

**Comment by nobuhiko** [comment]
会員データだと確認出来なかった

**Comment by nanasess** [comment]
これを移植すれば解決できそう
https://github.com/EC-CUBE/ec-cube/pull/5407

**Comment by nanasess** [comment]
会員情報のメモ覧に `テスト"可能"` と入力し、CSVダウンロードしてみたところ、エスケープ漏れは発生せず正常にダウンロードできました。
![image](https://github.com/user-attachments/assets/c070c12f-8765-4814-8b71-a1bb6cf4eba3)
PHP7.4, PHP8.4 で確認。
本事象は再現しないためクローズします
