### ISSUE TITLE
レスポンスヘッダ X-Content-Type-Options が出力されていない。

### ISSUE THREAD

**Issue by scubism-tech-share** [EC-CUBE/ec-cube2#48]
## 概要

X-Content-Type-Options:nosniffが出力されておらず、
クロスサイトスクリプティング等の攻撃被害につながる危険性がある。
## 対応

レスポンスヘッダ X-Content-Type-Options:nosniff を出力する。

**Comment by so-amuamu** [comment]
対応しましょう
ただし、「PDF生成→画面表示」などで影響が無いか、各ブラウザで念のため確認した方が良いですね
（これに対応すると、正しくContent-Typeを吐いてない場合に影響が出ます。）

**Comment by so-amuamu** [comment]
htaccessでは対応不十分と思われるのでreopenします
動作環境に依存しないよう、PHPからヘッダ出力するようにしないと駄目かなと

**Comment by nanasess** [comment]
#275 で修正済み
