### ISSUE TITLE
レスポンスヘッダ X-XSS-Protection が出力されていない。

### ISSUE THREAD

**Issue by scubism-tech-share** [EC-CUBE/ec-cube2#49]
## 概要

レスポンスヘッダにてX-XSS-Protection:1を出力することにより、
クロスサイトスクリプティング攻撃による被害を軽減することができる。

**Comment by so-amuamu** [comment]
これは入れるべきなのですが、管理画面では副作用がありそう。
要確認ですかね

**Comment by so-amuamu** [comment]
htaccessだけでは不十分。PHPからも出力する方が良いと思われる
関連　#48

**Comment by nanasess** [comment]
#275 で修正済み
