### ISSUE TITLE
How to check version details on current installed instance

### ISSUE THREAD

**Issue by tester000One** [EC-CUBE/ec-cube2#502]
How can we find the version details of the instance installed by docker on localhost and what is the default username password once instance is up and running using docker

**Comment by nanasess** [comment]
@tester000One 
Default username and password are admin/password.
Version number can be found in SC_Initial.php

https://github.com/EC-CUBE/ec-cube2/blob/master/data/class/SC_Initial.php#L38

**Comment by tester000One** [comment]
Thanks for the assistance @nanasess . This was really helpful. Have a wonderful day ahead :)
