### ISSUE TITLE
/html/install/index.phpのタイポ

### ISSUE THREAD

**Issue by akiran314** [EC-CUBE/ec-cube2#503]
https://github.com/EC-CUBE/ec-cube2/blob/261ef5d557647a210de2ee8d35b87fc57e63a4a6/html/install/index.php#L849
`default_storage_engine`とすべきところが`defaut_storage_engine`になっているためSQLがエラーとなり、インストールできない。
SC_DB_DBFactory_MYSQL.phpの方は大丈夫。
なお、このエラーが起きた時点で既に管理画面用ディレクトリの名前が「admin」から変更されているため、変更されたディレクトリ名を「admin」に戻さなければならないことに注意。

**Comment by nanasess** [comment]
@akiran314 ありがとうございます！ Pull Request しておきました。
インストーラの E2E テストがあるのですが、今までこの箇所でエラーになったこと無かったんですよね。ちゃんとエラーになって欲しいものです...
https://github.com/EC-CUBE/ec-cube2/runs/4638560474?check_suite_focus=true#step:14:78

**Comment by akiran314** [comment]
@nanasess 今回の環境は8.0.26でエラーになりましたので、MySQL8.0.xでテストしていないのかも知れません。これまでこの問題に当たった人が皆無というのも考えにくいですが、それほど多くの人が困っていなかったのなら幸いです。
