### ISSUE TITLE
SC_DB_DBFactory系クラスの継承ツリーにSC_DB_DBFactory_Exが入っていない

### ISSUE THREAD

**Issue by akiran314** [EC-CUBE/ec-cube2#519]
class SC_DB_DBFactory_MYSQL extends SC_DB_DBFactory
class SC_DB_DBFactory_PGSQL extends SC_DB_DBFactory

これらはSC_DB_DBFactory_Exを継承すべきところSC_DB_DBFactoryを継承しているため、SC_DB_DBFactory_Exが継承ツリーから外れており、SC_DB_DBFactory_Exの存在意義が無くなっているように思える。

**Comment by nanasess** [comment]
ありがとうございます。これは本当にそうなんですが、実運用でカスタマイズする場合は `SC_DB_Factory_(MYSQL|PGSQL)_Ex` を修正するので、さほど問題にならないのではないかと思っていますがどうでしょうか？

**Comment by akiran314** [comment]
確かに、MySQLとPostgreSQLを同時に使うことは極めて稀と思われるので、運用上は困る事はないでしょうね。
といういことで本件はクローズします。

**Comment by seasoftjapan** [comment]
私も過去に支障となった記憶はありませんが、さくっと6文字書き足すとかで直るなら、修正しても良いのかなと思いました。
それか、SC_DB_DBFactory_Ex 消すか。
