### ISSUE TITLE
受注管理>受注登録で必要な hidden が出力されない場合がある

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube2#543]
https://github.com/EC-CUBE/ec-cube2/blob/a47b46ec70ab977428f860feeeaa2f0db19a7620/data/Smarty/templates/admin/order/edit.tpl#L586-L604

上記のロジックでは、 `!empty($arrShipping.shipment_product_class_id)` の else の条件なので、`$arrShipping.shipment_product_class_id === null` となり、 section ループは発生しない。

`<!--{section name=item loop=1}-->` とするのが正しいのか要調査

**Comment by seasoftjapan** [comment]
`<!--{if $tpl_shipping_quantity > 1}-->` の `<!--{else}-->` じゃないでしょうか?

**Comment by nanasess** [comment]
https://github.com/EC-CUBE/ec-cube2/issues/787 で解消されていますのでクローズします
