### ISSUE TITLE
SC_Response::reload() 既存の問い合わせ文字列が二重でURLエンコードされる

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube2#574]
テストコード
```php
        if (!$_GET['redirect']) {
            SC_Response_Ex::reload(['redirect' => 1]);
            SC_Response_Ex::actionExit();
        }
```
`?debug=%E3%83%86%E3%82%B9%E3%83%88` にアクセスすると、
`?debug=%E3%83%86%E3%82%B9%E3%83%88&redirect=1` にリダイレクトされるべきところ、
`?debug=%25E3%2583%2586%25E3%2582%25B9%25E3%2583%2588&redirect=1` にリダイレクトされる。

**Comment by chihiro-adachi** [comment]
https://github.com/EC-CUBE/ec-cube2/pull/575 で対応
