### ISSUE TITLE
html/js/eccube.js に存在しないファイル eccube.js.map の記述がある

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube2#616]
Chrome デベロッパーツールを開いていると、eccube.js.map へのアクセスが発生する。しかし、存在しない。

通常はサーバー側で 404 エラーが発生して終わりだが、302 `Location: /` している環境で、購入手続き中に /shopping/payment.php に進むと `DELETE FROM "dtb_order_temp" WHERE order_temp_id = $1` が実行され /shopping/confirm.php を表示できずハマった。
(eccube.js.map や `Location: /` による / へのアクセスは、デベロッパーツールのネットワークタブに表示されない。)

そもそも `Location: /` はどうかと思うが、File Not Found を EC-CUBE で送出するカスタマイズをしているサイトでも、SC_Helper_Purchase::cancelPendingOrder() を呼んでいれば同様の事象は起き得る。

**Comment by nanasess** [comment]
eccube.js を minify した時に生成されるファイルですね。
パッケージに含めるようにしてもよいかもしれません。

**Comment by nanasess** [comment]
#631 で eccube.js を再ビルドしたついでに eccube.js.map も含めるようにしてみました

**Comment by seasoftjapan** [comment]
8ed22da5ea425bdd5c7c7a740dbdf7f887dfc10f アクセスログにて、404 -> 200 を確認しました。
```
::1 - - [16/Dec/2022:22:54:53 +0900] "GET /ec217/html/js/eccube.js.map HTTP/1.1" 404 487 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
::1 - - [16/Dec/2022:23:05:24 +0900] "GET /ec217/html/js/eccube.js.map HTTP/1.1" 200 231640 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

**Comment by nanasess** [comment]
#631 がマージされましたのでクローズします
