### ISSUE TITLE
商品管理　商品の並び替えが出来ない

### ISSUE THREAD

**Issue by yuki-ishihara** [EC-CUBE/ec-cube2#62]
### 概要

一番上の商品に対する「□番目へ移動」の指示が正常に反映されない。
しばらく動かしていると、正常に作動するようになる。  
また、商品の上下の移動は最初から可能。
### 発生個所

管理画面>商品管理>商品並び替え
### 頻度

初回のみと思われる

Masterをチェックアウトして確認しています。

**Comment by so-amuamu** [comment]
rank値がおかしくなる模様

**Comment by nanasess** [comment]
再現しないためクローズします
