### ISSUE TITLE
SC_Query_Ex::getSingletonInstance() 参照渡しが残っている

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube2#622]
「=& SC_Query」で grep すると、18箇所ほど。

実害ありそうなのは、以下か。
html/admin/load_module_config.php
html/test/upgrade/index.php

意図的に変更していないなら、コメント記載して欲しい。

他は、tests/class/helper 以下。(ここは無視で良い?)

**Comment by nanasess** [comment]
修正漏れだと思います
