### ISSUE TITLE
CentOS7 EOL に向けたシステム要件の変更

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube2#681]
CentOS7 の EOL が 2024年6月30日となっているため、システム要件の下限バージョン変更を検討する。
- PHP5.4.16 → PHP7.4.33

合わせて、 Smarty のバージョンアップを実施する(#615)

**Comment by nanasess** [comment]
ちなみに、 RHEL9 の PHP8.0 であれば 2032年までサポートされる模様
![image](https://user-images.githubusercontent.com/815715/218894546-224107ff-28ef-4df7-99c7-3adc4d6362d7.png)

**Comment by nobuhiko** [comment]
システム要件の変更にあわせて、2.18にするとかもありですよね。

**Comment by nanasess** [comment]
@nobuhiko はい、ありですね。

**Comment by seasoftjapan** [comment]
PHP 5.4 対応の EC-CUBE 2.17.3 をリリースする計画が無ければ、[master](https://github.com/EC-CUBE/ec-cube2/tree/master) はこの Issue を反映して、PHP 8 対応を強化する体制に移行する方が良いのではないかと思いますが、どうでしょうか？

**Comment by nanasess** [comment]
@seasoftjapan はい、今後は基本的にPHP8対応の強化で問題ないと思います。
master ブランチのシステム要件変更をマージするのは、 2024年6月30日以降で良いかなと思いましたが、もっと早めたい意向などありますか？

**Comment by nanasess** [comment]
@seasoftjapan 
以下のような感じでいかがでしょうか？
- master ブランチはシステム要件を変更し、 PHP7.4+ とする
- 現在の master からPHP5.4互換のブランチを作成し、2024年6月末に最終版のビルドのリリースタグを作成する
  - 互換性に問題のない PR もマージしておく

**Comment by seasoftjapan** [comment]
@nanasess はい。それでしたら、完璧だと思います。

**Comment by nanasess** [comment]
@seasoftjapan 
システム要件変更のPRしましたので、問題なければ approve おねがいします🙇‍♂️
https://github.com/EC-CUBE/ec-cube2/pull/854

**Comment by nanasess** [comment]
master ブランチは #854 で変更しましたのでクローズします
