### ISSUE TITLE
Weekly build ってどうなってますか?

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube2#752]
ここ数ヶ月間、EC-CUBE 2.17系の Weekly build が作成されていない気がするのですが、分かりますか?

**Comment by nanasess** [comment]
@seasoftjapan 今週は作成されたようです。
単に master へのマージが無かっただけですね。
(なかなか時間が取れず、メンテナンスが滞っておりすみません)

**Comment by seasoftjapan** [comment]
了解です。
[eccube2-weekly-20230822](https://github.com/EC-CUBE/ec-cube2/releases/tag/eccube2-weekly-20230822) 確認しました。
