### ISSUE TITLE
自動ロールバックをオンにして誤って決済処理中にステータスを変更するとオーダーが削除される

### ISSUE THREAD

**Issue by ttsuru** [EC-CUBE/ec-cube2#78]

**Comment by so-amuamu** [comment]
本筋からすると、自動ロールバックON時に
管理画面上で「他の状態→決済処理中」に変更出来る事自体が状態遷移の仕様と矛盾するのが問題と思われる。
他の状態→決済処理中　を管理画面から変更出来なくするべきと思われます

**Comment by nanasess** [comment]
2系の仕様ということでクローズします
