### ISSUE TITLE
PHP8 で「受注管理＞受注登録」画面がシステムエラー

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube2#787]
```
Fatal error(E_ERROR): Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /**/data/Smarty/templates_c/admin/804dc0e4d49a6f63dd14a13f26304a7894724e1e_0.file.edit.tpl.php:930
```

PHP 8.0、8.1、8.2 いずれも同様の様子。

新規入力で発生を確認。
既存の受注情報を編集する場合は発生しない様子。

section 使わず、foreach 使えば回避できるけど、項目ごとに別の配列だから、それはそれで微妙になる。
(もっと根本的には、このデータは2次元配列として foreach で扱いたいれど、それはまた別の話。)

とりあえず、テンプレートで IF 分岐 (!empty()) すれば、回避できそう。

多分、本来は、SC_FormParam で項目が配列かをきっちり弁別すべき。そして、配列なら null じゃなくて、[] を返して欲しい。そしたら、テンプレートで IF 分岐とか考慮しなくて済む。本件用の応急策としては、SC_FormParam から値を受け取った後で、キャストするのも候補かも。

**Comment by seasoftjapan** [comment]
上 (if-else の if の中) を見たら `<!--{if !empty($arrShipping.shipment_product_class_id)}-->` してたので、同じ対応にします。

**Comment by nanasess** [comment]
#788 で対応済みですのでクローズします
