### ISSUE TITLE
未使用ファイル dockerbuild/php.ini 削除

### ISSUE THREAD

**Issue by seasoftjapan** [EC-CUBE/ec-cube2#839]
docker build で使われると推測していたが、使われていなそう。

**Comment by seasoftjapan** [comment]
@nanasess https://github.com/EC-CUBE/ec-cube2/commit/9a3476501355b14601a4cdd0e99f9f36f5f4d41f で追加されていると思いますが、使われているかなど分かりますか?

**Comment by nanasess** [comment]
@seasoftjapan 使われてないと思いますので削除しても問題ないと思います
