### ISSUE TITLE
#296 商品一覧, 商品詳細のパフォーマンス改善の動作に関して

### ISSUE THREAD

**Issue by clicktx** [EC-CUBE/ec-cube2#897]
@nanasess 

#296 の動作に関して

## Test

tests/class/SC_Product/SC_Product_listsTest.php

``` php
        $this->actual = $this->objProducts->lists($this->objQuery, array(1001, 1002));

        $this->verify('商品一覧');
```
引数を与えてもマッチ0件となりテストが通らなくなります。
正しい挙動でしょうか？

## 考察

data/class/db/SC_DB_DBFactory.php

``` php
    public function alldtlSQL($where_products_class = '', $product_ids = array())
    {
        if (!SC_Utils_Ex::isBlank($where_products_class)) {
            $where_products_class = 'AND (' . $where_products_class . ')';
        }

        $dtb_products_table = 'dtb_products';
        $product_id_cause = '';

        // dtb_products_class の Full scan を防ぐため,
        // 商品IDが特定できている場合は, 先に product_id で対象を絞り込む
        if (count($product_ids) > 0) {
            $in = SC_Utils_Ex::repeatStrWithSeparator('?', count($product_ids));
            $product_id_cause = ' AND product_id IN ('.$in.')';
            $dtb_products_table = ' ( SELECT * FROM dtb_products WHERE product_id IN ('.$in.') ) AS dtb_products';
        }
```

上記コードでIN句を

``` php
$in = SC_Utils_Ex::repeatStrWithSeparator('?', count($product_ids));
```
でプレースホルダーにして最終的にSQLを返していますが、 $arrWhereVal相当の引数が与えられていないため何も返さないです。

-----

`SC_Product::lists()`の中で呼ばれている

``` php
$res = $objQuery->select($col, static::alldtlSQL('', $product_ids));
```

に `$arrWhereVal` を与えてもうまく動作しなそうです。

プレースホルダーにしないで直接`product_id`をIN句にする意図だったのでしょうか？

```SQL
... WHERE product_id IN (1001, 1002) ... 
```

**Comment by nanasess** [comment]
@clicktx わかりづらくてすみません。
SC_Product::lists() の第二引数を使用するケースは、以下のように SC_DB_DBFactory::alldtlSQL()  が利用するエイリアスである `alldtl.product_id` に対応する WHERE 句が必要になります。
https://github.com/EC-CUBE/ec-cube2/blob/32c42a33b2d7cdfebb79b3cadbe001a064447fcc/data/class/SC_Product.php#L174-L183

SC_Product::lists() の第二引数はプレースホルダーを生成するためのみに使用します。
通常は SC_Query::setWhere() を使用して `$arrWhereVal` 相当の変数を設定します。
以下のようにすればテストも通ると思います

```php
        $this->objQuery->setWhere('product_id IN (?, ?)', [1001, 1002]);
        $this->actual = $this->objProducts->lists($this->objQuery);
```

**Comment by clicktx** [comment]
@nanasess ありがとうございます。
なるほど、SC_Product::lists()を使わないで、 ラッパーメソッドの SC_Product::getListByProductIds() を使う感じですね。

tests/class/SC_Product/SC_Product_listsTest.php で
```
$this->actual = $this->objProducts->getListByProductIds($this->objQuery, array(1001, 1002));
```

としても、SC_Product::getListByProductIds()内で配列のキーを変えているので通らないようですが、概ね理解できました。
ありがとうございました！
