### ISSUE TITLE
商品一覧の価格順並び替えが登録されていない商品規格に影響される

### ISSUE THREAD

**Issue by zenith6** [EC-CUBE/ec-cube2#93]
商品一覧で価格順に表示した際に、登録していない規格の価格を含めた状態で並び替えられます。
再現手順は以下の通りです。
1.  2.13.5 をインストール。
2. 商品ID:1 アイスクリームの商品管理＞商品登録(商品規格)を開く。
3. いずれかの規格の販売価格を `1` に変更、登録のチェックボックスを外し、登録。
4. 商品一覧を開き、`価格順` で並び替える。

`SC_Product::findProductIdsOrder()` が、`dtb_products_class.del_flg` を考慮していないための現象と思われます。

EC-CUBE 2.13.4, 2.13.5 で確認。

**Comment by nanasess** [comment]
#261 で修正済ですのでクローズします
