### ISSUE TITLE
adminテンプレートにあるペイジェントモジュール連携用のコードは意図したもの？

### ISSUE THREAD

**Issue by clicktx** [EC-CUBE/ec-cube2#967]
https://github.com/EC-CUBE/ec-cube2/blob/5cfe357db66d876607742ceabcb4603674f8aa96/data/Smarty/templates/admin/order/index.tpl#L323-L327

相当前からこのコードが残っているのですが、これは意図して残してあるものなのでしょうか？
511cc24781d295b8c99c33515fdb7b18485be5eb までは無かったみたいですが、 7f423c22c8faf4d9844344da078d6b25f81342b5 から入っているようです。

**Comment by seasoftjapan** [comment]
直近のモジュールだと `mdl_paygent\files\templates\admin\paygent_order_index.tpl` に移動している様子なので、空回りしていそうですね。

2011年10月頃のモジュール (2.4向け?) では存在しますね。

**Comment by clicktx** [comment]
> 2.4向け

そうなのですね。2.4用のペイジェントモジュールのコードは入手できないので確認できませんが、2.17用のコードを斜め読みした感じだと該当のページのテンプレートはそっくり置き換えているっぽいので必要なさそうに見えますね。

**Comment by nanasess** [comment]
@clicktx @seasoftjapan 
他にも過去のモジュール連携用のコードがいくつかあるのですが、すべて不要だと思いますので PR いただけると助かります🙏
https://github.com/search?q=repo%3AEC-CUBE%2Fec-cube2%20smarty.const.MODULE_REALDIR&type=code

**Comment by nanasess** [comment]
#972 でマージしましたのでクローズします
