### ISSUE TITLE
登録メール送信時の警告 SC_Helper_Mail::sfSendRegistMail()

### ISSUE THREAD

**Issue by clicktx** [EC-CUBE/ec-cube2#982]
https://github.com/EC-CUBE/ec-cube2/blob/d9568e76922661a893ab8658b8c4fd1fb079b155/data/class/helper/SC_Helper_Mail.php#L379

該当部分で警告が出ます。
Warning(E_WARNING): get_object_vars() expects parameter 1 to be object, array given

`assignobj()`ではなく`assignarray()`を使うのが正しいのでしょうか？

`$objMailText->assignarray($arrCustomerData);`

また、関連して、`assignarray()`で検索すると下記のコードが見た感じArrayを引数にしているのですが、実際にはObjectなので警告が出ません。
`$objTplVar`などに変数名を変えておいた方が良いのかも知れません。

https://github.com/EC-CUBE/ec-cube2/blob/d9568e76922661a893ab8658b8c4fd1fb079b155/data/class/helper/SC_Helper_Mail.php#L194

**Comment by seasoftjapan** [comment]
動作未検証ですが、以下が必要かも疑問に思いました。
https://github.com/EC-CUBE/ec-cube2/blob/d9568e76922661a893ab8658b8c4fd1fb079b155/data/class/helper/SC_Helper_Mail.php#L376-L377

**Comment by nanasess** [comment]
会員登録メールは name01, name02 しか使ってないので `assignobj` は無視されてるようですね。
削除してしまうのが良いかも

**Comment by seasoftjapan** [comment]
カスタマイズで email, company_name あたりを追加するとかは割合あるので、assignarray() で支障なく動作するのであれば、その方がロジック変更無しでカスタマイズできて便利とは思います。

本当は、SC_Helper_Mail::sfSendOrderMail() の `$arrTplVar->arrCustomer` みたいな方が分かりやすいですね。
https://github.com/EC-CUBE/ec-cube2/blob/d9568e76922661a893ab8658b8c4fd1fb079b155/data/class/helper/SC_Helper_Mail.php#L161
https://github.com/EC-CUBE/ec-cube2/blob/d9568e76922661a893ab8658b8c4fd1fb079b155/data/Smarty/templates/default/mail_templates/order_mail.tpl#L125

**Comment by clicktx** [comment]
> 本当は、SC_Helper_Mail::sfSendOrderMail() の `$arrTplVar->arrCustomer` みたいな方が分かりやすいですね。
> https://github.com/EC-CUBE/ec-cube2/blob/d9568e76922661a893ab8658b8c4fd1fb079b155/data/Smarty/templates/default/mail_templates/order_mail.tpl#L125

分かりやすいし、使いやすそうです。
customerに関する事を出力したい時多いですし。
ただ、他の箇所も同じ仕様にしたくなり、メールテンプレートも修正する必要があるため互換性が無くなりそうですね。
メールテンプレートカスタマイズしている勢としては気づきにくい変更となりそうです。。。
前のassignも残しつつ、追加するなら問題なさそうですかね。

```
$objMailText = new SC_SiteView_Ex();
$objMailText->setPage($this->getPage());
$objMailText->assign('CONF', $CONF);
$objMailText->assign('name01', $arrCustomerData['name01']);
$objMailText->assign('name02', $arrCustomerData['name02']);
$objMailText->assign('uniqid', $arrCustomerData['secret_key']);
$objMailText->assign('arrCustomer', $arrCustomerData);
```


> 動作未検証ですが、以下が必要かも疑問に思いました。
> 
> https://github.com/EC-CUBE/ec-cube2/blob/d9568e76922661a893ab8658b8c4fd1fb079b155/data/class/helper/SC_Helper_Mail.php#L376-L377

assignarray()で動作するなら不要になりそうな気はします。

**Comment by nanasess** [comment]
@clicktx @seasoftjapan 
以下のような感じでいかがでしょう？

- 実装は `assignarray` に修正する
- name01, name02 の assign は削除
- 拡張用として `arrCustomer` も使えるようにする(何故この変数があるかをコメントしておく)

**Comment by seasoftjapan** [comment]
テンプレート側も標準で `$arrCustomer` を使うのはどうでしょうか?
``` diff
-<!--{$name01}--> <!--{$name02}--> 様
+<!--{$arrCustomer.name01}--> <!--{$arrCustomer.name02}--> 様
```
``` diff
-<!--{$smarty.const.HTTPS_URL}-->regist/<!--{$smarty.const.DIR_INDEX_PATH}-->?mode=regist&id=<!--{$uniqid}--><!--{$etc_value}-->
+<!--{$smarty.const.HTTPS_URL}-->regist/<!--{$smarty.const.DIR_INDEX_PATH}-->?mode=regist&id=<!--{$arrCustomer.secret_key}--><!--{$etc_value}-->
```

互換性を考慮すると、ロジックは以下のイメージでしょうか。(動作未検証)
``` php
$objMailText = new SC_SiteView_Ex();
$objMailText->setPage($this->getPage());
$objMailText->assign('CONF', $CONF);
$objMailText->assign('arrCustomer', $arrCustomerData);

// 旧テンプレート互換用 https://github.com/EC-CUBE/ec-cube2/issues/982
$objMailText->assignarray($arrCustomerData);
$objMailText->assign('uniqid', $arrCustomerData['secret_key']);
```

**Comment by nanasess** [comment]
@seasoftjapan 過去のテンプレートもそのまま動くようでしたら、こちらがよさそうですね

**Comment by clicktx** [comment]
- customer_regist_mail.tpl
- customer_mail.tpl

関係するテンプレート、２つあるのですね。

テスト書いたのですが、
62d44b084b9c12d0120623ada4e6b5c9f6a0408a

両者のテンプレート、宛名部分が若干違っている（姓と名の間に半角スペースあり、なし）のですが、そのままにしています。

**Comment by clicktx** [comment]
https://github.com/EC-CUBE/ec-cube2/blob/d9568e76922661a893ab8658b8c4fd1fb079b155/data/class/helper/SC_Helper_Mail.php#L383-L389

本件とは全く関係ないのですが、このメールタイトルの日本語が気になっています。
自分は「会員登録が完了しました」に直して使っていますが。。。

**Comment by clicktx** [comment]
> テンプレート側も標準で `$arrCustomer` を使うのはどうでしょうか?
> 
> ```diff
> -  様
> +  様
> ```
> 
> ```diff
> -regist/?mode=regist&id=
> +regist/?mode=regist&id=
> ```
> 
> 互換性を考慮すると、ロジックは以下のイメージでしょうか。(動作未検証)
> 
> ```
> $objMailText = new SC_SiteView_Ex();
> $objMailText->setPage($this->getPage());
> $objMailText->assign('CONF', $CONF);
> $objMailText->assign('arrCustomer', $arrCustomerData);
> 
> // 旧テンプレート互換用 https://github.com/EC-CUBE/ec-cube2/issues/982
> $objMailText->assignarray($arrCustomerData);
> $objMailText->assign('uniqid', $arrCustomerData['secret_key']);
> ```

こちらに変更してテスト通ります。

**Comment by seasoftjapan** [comment]
> 両者のテンプレート、宛名部分が若干違っている（姓と名の間に半角スペースあり、なし）のですが、そのままにしています。

関連した Issue を登録しました。https://github.com/EC-CUBE/ec-cube2/issues/991

**Comment by clicktx** [comment]
https://github.com/EC-CUBE/ec-cube2/blob/fc5a36a25f2fff5179670351d65f890228b86e13/data/class/helper/SC_Helper_Mail.php#L382-L383

ここの条件式に関してコメント書いたのですが、こちらにも残しておきます。

https://github.com/EC-CUBE/ec-cube2/pull/989#issuecomment-2331118275
