### ISSUE TITLE
複数のテストファイルで使われているtearUp()、正しくはtearDown()？

### ISSUE THREAD

**Issue by clicktx** [EC-CUBE/ec-cube2#983]
https://github.com/EC-CUBE/ec-cube2/blob/d9568e76922661a893ab8658b8c4fd1fb079b155/tests/class/helper/SC_Helper_Address/SC_Helper_Address_deleteAddressTest.php#L8-L21

testを見ていたら`tearUp()`という関数が複数のテストファイルで使われている（記述されている）ようです。
正しくは`tearDown()`ですかね？？
親クラスには該当の関数は無さそうだし、呼び出されないので無害かと思いますが。

https://github.com/EC-CUBE/ec-cube2/blob/d9568e76922661a893ab8658b8c4fd1fb079b155/tests/class/helper/SC_Helper_Address/SC_Helper_Address_TestBase.php#L15-L18

は書かなくても親クラスのものが呼ばれるようなのでテストを実行するにあたっては問題ないようです。

**Comment by nanasess** [comment]
11年前からの名残りですね。単なる typo だと思います。

**Comment by clicktx** [comment]
後ほど修正してPRします
