### ISSUE TITLE
商品別税率機能の不具合

### ISSUE THREAD

**Issue by nanasess** [EC-CUBE/ec-cube2#99]
trac のほうにしか登録されていなかったので備忘録として。
http://svn.ec-cube.net/open_trac/ticket/2616

http://xoops.ec-cube.net/modules/newbb/viewtopic.php?viewmode=thread&topic_id=15055&forum=10&post_id=67418#forumpost67418

> 一覧ではproduct_class_idがsfCalcIncTaxに対して渡されていない事に関係する不具合みたいです。

**Comment by nomoto-neo** [comment]
2.13で、商品別税率が商品一覧と商品詳細に反映されない件ですが、軽減税率対応のためにも対処しなければならない問題でしたので独自に修正しました。

少しでも当プロジェクトに貢献したいのですが、Githubの扱いが不慣れでプロジェクトへの反映方法が分からないため、間違ったら困るのでこちらにdiffを貼り付けさせてください。

OPTION_PRODUCT_TAX_RULE = 0 の場合は商品個別設定値を無視して基本税率を適用します。
TAX_RULE_PRIORITY の設定値は2.13でどのように機能しているのか不明だったため考慮していません。
[product_list_and_detail_taxrate_bug_fix.diff.txt](https://github.com/EC-CUBE/eccube-2_13/files/3466155/product_list_and_detail_taxrate_bug_fix.diff.txt)

**Comment by seasoftjapan** [comment]
最近、商品別税率機能を検証しましたが、色々と問題ありますね・・・

@nomoto-neo さんの対応された部分、私も SQL での処理が妥当かもと思っていました。

あと、商品登録で、税率未設定を登録できなかったり、端数処理まで登録されるのは、どうなんだろと疑問に思いました。(そもそも、dtb_tax_rule.tax_rate は良くない印象です。2.12 に dtb_products_class.tax_rate を付け加えた経験がありますが、そっちの方が勝手が良かったです。)
CSV対応できていないのも、実運用を考えると痛いですね・・・

**Comment by nomoto-neo** [comment]
product_class_id単位の情報なのにdtb_tax_ruleに値を持たせている事で、確かに修正していて、わざわざJOINしたりサブクエリを使わないといけないのが、修正を尚更難しくしている印象でした。

スマートにdtb_products_classにtax_rateを持たせるべきだと私も考えましたが、2.13からの修正箇所が大きすぎて、軽減税率開始2ヶ月を切った現時点でそこまでの修正コストは掛けれなかったです。

**Comment by nanasess** [comment]
カテゴリや商品単位で税率を指定できるよう、このような実装になってるんですよね。
また、この機能を開発していた当初は国際化版のバージョンもあった関係で、国や都道府県ごとに税率設定可能なデータ構造になってます

**Comment by nobuhiko** [comment]
@nanasess さん、このチケット対応します？

**Comment by nanasess** [comment]
@nobuhiko `SC_Product::setIncTaxToProduct()` で `product_class_id` を渡せないかと修正を試みてますー

**Comment by nobuhiko** [comment]
関連事項としては、
- 納品書
の「区分記載請求書等」対応が必要になる

**Comment by nanasess** [comment]
商品規格ごとの税率設定を削除することで対応 #301
